# Generated by Django 3.1.7 on 2021-03-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Summary', models.TextField()),
                ('Article', models.TextField()),
                ('Image', models.TextField()),
                ('Link', models.TextField()),
                ('Date', models.TextField()),
            ],
        ),
    ]
